# Generated by Django 4.2.4 on 2023-10-08 01:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_habilidades_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
